Binary wrappers improved.

diff --git a/bin/sendjob b/bin/sendjob
--- a/bin/sendjob
+++ b/bin/sendjob
@@ -1,24 +1,14 @@
-#!/bin/sh
+#!/bin/sh -e
 #
-# $Id$
+# $Id: requeue 784 2004-10-15 03:10:46Z jorge $
 #
 
-if [ ! $DRQUEUE_ROOT ]; then
-  echo ERROR: DRQUEUE_ROOT not set in environment
-  exit 1
-fi
+SHLIB=$DRQUEUE_ROOT/bin/shlib
 
-if [ ! $DRQUEUE_MASTER ]; then
-  echo ERROR: DRQUEUE_MASTER not set in environment
-  exit 2
-fi
+. $SHLIB || die "ERROR: Could not read $SHLIB"
 
-SJ_CMD=$DRQUEUE_ROOT/bin/sendjob.`uname -s`
+check_environment
 
-if [ ! -x $SJ_CMD ]; then
-  echo ERROR: sendjob for your platform \(sendjob.`uname -s`\) does not exist in $DRQUEUE_ROOT/bin.
-  echo Perhaps you did not install it \(make miniinstall or make install\).
-  exit 3
-fi
+wrapper_cmd "$BASETOOL"
 
-$SJ_CMD $*
+$WRAP_CMD $*
diff --git a/bin/slave b/bin/slave
--- a/bin/slave
+++ b/bin/slave
@@ -1,29 +1,19 @@
-#!/bin/sh
+#!/bin/sh -e
 #
-# $Id$
-#
-# Slave starting program that restarts the slave after failure
+# $Id: requeue 784 2004-10-15 03:10:46Z jorge $
 #
 
-if [ ! $DRQUEUE_ROOT ]; then
-  echo ERROR: DRQUEUE_ROOT not set in environment
-  exit 1
-fi
+SHLIB=$DRQUEUE_ROOT/bin/shlib
 
-if [ ! $DRQUEUE_MASTER ]; then
-  echo ERROR: DRQUEUE_MASTER not set in environment
-  exit 2
-fi
+. $SHLIB || die "ERROR: Could not read $SHLIB"
 
-SLAVE_CMD=$DRQUEUE_ROOT/bin/slave.`uname -s`
+check_environment
 
-if [ ! -x $SLAVE_CMD ]; then
-  echo ERROR: slave for your platform \(slave.`uname -s`\) does not exist in $DRQUEUE_ROOT/bin.
-  echo Perhaps you did not install it \(make miniinstall or make install\).
-  exit 3
-fi
+wrapper_cmd "$BASETOOL"
 
+## Being the slave
 while [ 1 ]; do
-  $SLAVE_CMD $*
-  sleep 60
+    $WRAP_CMD $*
+    # TODO: log when it dies and restarts
+    sleep 30
 done
